### ISSUE TITLE
Possible issues to work on

### ISSUE THREAD

**Issue by jps12** [FGA-GCES/rasa#104]
# Sprint 1

**Description of Problem**:
I open this issue to comment possible issues from original repository rasa that we could work on. 

**Overview of the Solution**:
List many possible issues on commentaries.

**Comment by jps12** [comment]
Possible issues encountered by @ErickGiffoni 

- [Rasa 7956](https://github.com/RasaHQ/rasa/issues/7956): macOS related
- [Rasa 5657](https://github.com/RasaHQ/rasa/issues/5657)
- [Contributors 15](https://github.com/RasaHQ/contributors/issues/15)
- [Contributors 17](https://github.com/RasaHQ/contributors/issues/17)
- [Rasa 7250](https://github.com/RasaHQ/rasa/issues/7250)

**Comment by juliolitwin** [comment]
- [Rasa 7401](https://github.com/RasaHQ/rasa/issues/7401)

**Comment by ErickGiffoni** [comment]
Hey, I'm taking Rasa #7956 and I'll open a pull request soon.

**Comment by ErickGiffoni** [comment]
> Hey, I'm taking Rasa [RasaHQ#7956](https://github.com/RasaHQ/rasa/issues/7956) and I'll open a pull request soon.

Done !

https://github.com/RasaHQ/rasa/pull/9296

**Comment by caue96** [comment]
Issues done:

- [Rasa 7956](https://github.com/RasaHQ/rasa/issues/7956): macOS related -> Done by @ErickGiffoni , pull request [here](https://github.com/RasaHQ/rasa/pull/9296)
- - [Contributors 17](https://github.com/RasaHQ/contributors/issues/17): NLU training -> Done by @juliolitwin, pull request [here](https://github.com/RasaHQ/NLU-training-data/pull/70)
