### ISSUE TITLE
Sprint 2

### ISSUE THREAD

**Issue by jps12** [FGA-GCES/rasa#116]
## Planejamento

|Pareamento|Issues que estão sendo trabalhadas|Issues entregues|
|---|---|---|
|@juliolitwin @jps12| <li><a href="https://github.com/RasaHQ/rasa/issues/7590">Issue7590</a></li> <br> |  |
|@ErickGiffoni @caue96 @andrelucasf| <ul><li><a href="https://github.com/RasaHQ/contributors/issues/15">Contributors 15</a></li> <br> <li><a href="https://github.com/RasaHQ/rasa/issues/9342">Rasa 9342</a></li></ul> |  |

### Resultados

* Rasa 9342 - Problema relativo a uma versão bem específica do macOS para utilizar o Rasa. Devido a falta de interação dos mantenedores em expressar maiores esclarecimentos na issue, decidiu-se colocá-la em espera;

* A sprint 2 também foi marcada pela execução do primeiro trabalho individual sobre configuração e isolamento de ambiente, utilizando Docker. Por causa da dificuldade enfrentada com o trabalho, além do enunciado do mesmo ter sido modificado após 1 semana de trabalho, gastou-se mais tempo e esforço para realizar o trabalho 1 em comparação à resolução de issues do Rasa.

* Contributors 15 - Uma leitura inicial sobre a issue foi feita. Após isso, a abordagem foi entender como estava organizada a estrutura de *intents* do *weather folder* e quais dados já haviam lá. Além disso, um breve estudo sobre como escrever *intents* e dados de treinamento foi feita. Após isso, o trabalho foi iniciado. O *pull request* está em [Rasa NLU #72](https://github.com/RasaHQ/NLU-training-data/pull/72)

**Comment by caue96** [comment]
Dependencies issues from sprint 1:

- [Rasa 5657](https://github.com/RasaHQ/rasa/issues/5657)
- [Contributors 15](https://github.com/RasaHQ/contributors/issues/15)
- [Rasa 7250](https://github.com/RasaHQ/rasa/issues/7250)

**Comment by ErickGiffoni** [comment]
Finalizada
