### ISSUE TITLE
Sprint 3

### ISSUE THREAD

**Issue by ErickGiffoni** [FGA-GCES/rasa#120]
## Planejamento

**Início**: 31/08/21
**Término**: 09/09/21

|Pareamento|Issues que estão sendo trabalhadas|Issues entregues|
|---|---|---|
|@juliolitwin @jps12| <li>#9393 |  |
|@ErickGiffoni @caue96 @andrelucasf|  <li>#7250<br><li>#5657 |  |

### Resultados

**Pull Requests**

- Solving Issue 7250: PR https://github.com/RasaHQ/rasa/pull/9543
  - Also related to previous PR #7839
  - Author: @ErickGiffoni 

- Previous PR #9296 : conversation continued, as there were some trouble regarding leftover files from a merge. We are still trying to sort things out.

- Solving Issue 5657: PR https://github.com/RasaHQ/rasa/pull/9567
  - Related to previous PR #8332
  - Author: @ErickGiffoni 
  - 
- Solving Issue 9393: PR https://github.com/RasaHQ/rasa/pull/9393
  - Author: @juliolitwin 

**Novas issues abertas**

- Rasa #9549 : problems while trying to use Rasa with **Docker**, via ```make build-docker```.

**Comment by ErickGiffoni** [comment]
Rasa 7250 - PR feito

**Comment by caue96** [comment]
Possible issues at Rasa projects to be solved:

- [Financial Demo - #52](https://github.com/RasaHQ/financial-demo/issues/52);
- [Rasa - #3055](https://github.com/RasaHQ/rasa/issues/3055);
- [Rasa - #3919](https://github.com/RasaHQ/rasa/issues/3919);
- [Rasa - #4585](https://github.com/RasaHQ/rasa/issues/4585);
- [Rasa - #2927](https://github.com/RasaHQ/rasa/issues/2927);
- [Rasa - #5845](https://github.com/RasaHQ/rasa/issues/5845);
- [Rasa - #5668](https://github.com/RasaHQ/rasa/issues/5668);
- [Rasa - #301](https://github.com/RasaHQ/rasa/issues/301).

**Comment by ErickGiffoni** [comment]
Closing. Deadline reached.
