### ISSUE TITLE
Log warning if lookup tables are not used correctly #5956

### ISSUE THREAD

**Issue by iurisevero** [FGA-GCES/rasa#13]
# Log warning if lookup tables are not used correctly

## Description
Issue to discuss the ideias and progress about the resolution of Rasa's issue [#5956](https://github.com/RasaHQ/rasa/issues/5956)

**Comment by iurisevero** [comment]
Sor far we're looking to documentation and code to understand about what the issue is referring to.
The links below looks useful:

https://rasa.com/docs/rasa/nlu-training-data#training-examples
https://rasa.com/docs/rasa/reference/rasa/nlu/featurizers/sparse_featurizer/regex_featurizer#regexfeaturizer-objects
https://blog.rasa.com/improving-entity-extraction/

**Comment by santosm46** [comment]
There is an example (knowledgebasebot) using lookup tables at the end of [this file](https://github.com/FGA-GCES/rasa/blob/2574c46e9576607a7b8de39f823ff3e5c01a475c/examples/knowledgebasebot/data/nlu.yml#L59), maybe we should change from
```
- lookup: hotel
  examples: |
    - Hilton
    - B&B
    - Berlin Wall Hostel
    - City Hotel
    - Jugendherberge
    - Berlin Hotel
```
to
```
- lookup: hotel
  examples: |
```
or
```
- lookup: hotel
```
to replicate the situation then try to fix it.

**Comment by santosm46** [comment]
I changed the lookup from knowledgebasebot to this:
```
- lookup: hotel
```
and this is what I got:
![image](https://user-images.githubusercontent.com/48760953/108638734-7353dd80-746f-11eb-815e-59c0c33459a0.png)
As seen in yellow, it shows "'lookup: hotel' doesn't have any examples. It will be skipped." to the user, I'm not sure if this is what the issue #5956 was refering to, and it's already done.

**Comment by santosm46** [comment]
I read the comments from the main issue, and it turns out the problem is quite different, so I changed the methods `train` and `_text_features_with_regex` to check if it found any feature and show a warning, as discussed in the issue. The changes can be seen in [this commit](https://github.com/FGA-GCES/rasa/commit/38ebfee1013e5d4474b0070e5918920ab68f5d8b).
But some changes need to be done.

**Comment by guilherme-mendes** [comment]
Wouldn't it be necessary to verify that the sentence_features method is also null for all training examples?

**Comment by guilherme-mendes** [comment]
I just changed the log notice [format](https://github.com/FGA-GCES/rasa/commit/c32713a9c4d6e45de0f65f114184577d000970fe) and it seems to be ok. What do you think, @arthurTemporim ?

**Comment by iurisevero** [comment]
Guys, I got a little further in our issue to validate if what we're doing was right and I figure out that this issue is from [Rasa 1.10.2](pypi.org/project/rasa/1.10.2/). So I searched into this version files and found that they didn't have a parse validator of NLU data, just a check if the file had a valid JSON or YAML.

In the updated version they've made the RasaYAMLReader class, which parses all NLU data files and validates things like Lookup tables and regex, so I don't think our issue still up.

(Also, I figure out that our solution didn't work, so... Win-win  :grimacing:)

[Rasa 1.10.2 validator](https://github.com/RasaHQ/rasa/blob/1.10.2/rasa/utils/validation.py)
[Rasa 2.3.2 parser/validator](https://github.com/RasaHQ/rasa/blob/2.3.2/rasa/shared/nlu/training_data/formats/rasa_yaml.py)

**Comment by guilherme-mendes** [comment]
I agree with your analysis @iurisevero.
